/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkinghaussystem;

import Dao.DBOperations;
import ParkhausClasses.Parketage;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tn
 */
public class EtageHinzufügenLoeschen extends javax.swing.JFrame {

    /**
     * Creates new form EtageHinzufügenLoeschen
     */
    public EtageHinzufügenLoeschen() {
        initComponents();
        btnSpeichern.setEnabled(false);
    }

    public void validateField() {
        String kategorie = txtEtagenName.getText();
        if (!kategorie.equals("")) {
            btnSpeichern.setEnabled(true);
        } else {
            btnSpeichern.setEnabled(false);
        }
    }

    public void updateEtagenTable() {
        DefaultTableModel model = (DefaultTableModel) etagenTable.getModel();
        model.setRowCount(0); // Löscht alle vorhandenen Zeilen

        List<String> etagenNamen = DBOperations.getAlleEtagenNamen();

        for (String name : etagenNamen) {
            model.addRow(new Object[]{name}); // Nehmen Sie an, dass die Tabelle jetzt nur eine Spalte hat
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEtagenName = new javax.swing.JTextField();
        btnSpeichern = new javax.swing.JButton();
        btnEntfernen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        etagenTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Etagenname");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 130, 30));

        txtEtagenName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        txtEtagenName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEtagenNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtEtagenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 270, 30));

        btnSpeichern.setBackground(new java.awt.Color(58, 101, 143));
        btnSpeichern.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnSpeichern.setForeground(new java.awt.Color(255, 255, 255));
        btnSpeichern.setText("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });
        getContentPane().add(btnSpeichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        btnEntfernen.setBackground(new java.awt.Color(58, 101, 143));
        btnEntfernen.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnEntfernen.setForeground(new java.awt.Color(255, 255, 255));
        btnEntfernen.setText("Abbrechen");
        btnEntfernen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntfernenActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntfernen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 100, 30));

        etagenTable.setBackground(new java.awt.Color(153, 153, 153));
        etagenTable.setForeground(new java.awt.Color(0, 0, 0));
        etagenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Etagenname"
            }
        ));
        etagenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etagenTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(etagenTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 410, 480));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 20, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Klicken Sie auf eine Etage in der Tabelle, um sie zu löschen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("_");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 20, 20));

        jButton1.setBackground(new java.awt.Color(58, 101, 143));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Zurück zu Admin Verwaltung Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 523, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/Backgroundmoyen.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        // TODO add your handling code here:
        String etagenName = txtEtagenName.getText();
        if (!etagenName.isEmpty()) {
            DBOperations.addEtage(etagenName);
            updateEtagenTable();

        }

    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void txtEtagenNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEtagenNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtEtagenNameKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) etagenTable.getModel();
        List<Parketage> etagenListe = DBOperations.getAlleEtagen();
        for (Parketage etage : etagenListe) {
            dtm.addRow(new Object[]{etage.getId(), etage.getEtagenName()});
        }
    }//GEN-LAST:event_formComponentShown

    private void etagenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etagenTableMouseClicked
        // TODO add your handling code here:
        int index = etagenTable.getSelectedRow();
        TableModel model = etagenTable.getModel();
        int id = Integer.parseInt(model.getValueAt(index, 0).toString());
        String name = model.getValueAt(index, 1).toString();
        int a = JOptionPane.showConfirmDialog(null, "Wollen Sie wirklich löschen " + name + " Etage", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            boolean erfolg = DBOperations.deleteEtage(id);
            if (erfolg) {
                JOptionPane.showMessageDialog(null, "Etage wurde gelöscht.");

                ((DefaultTableModel) model).removeRow(index);
            } else {
                JOptionPane.showMessageDialog(null, "Fehler beim Löschen der Etage.");
            }
        }
    }//GEN-LAST:event_etagenTableMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnEntfernenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntfernenActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnEntfernenActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setExtendedState(EtageHinzufügenLoeschen.ICONIFIED);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AdminVerwaltung().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtageHinzufügenLoeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtageHinzufügenLoeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtageHinzufügenLoeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtageHinzufügenLoeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtageHinzufügenLoeschen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntfernen;
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JTable etagenTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEtagenName;
    // End of variables declaration//GEN-END:variables
}
