/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkinghaussystem;

import Dao.DBOperations;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author tn
 */
public class ParkplatzVerlassen extends javax.swing.JFrame {

    /**
     * Creates new form ParkplatzVerlassen
     */
    public ParkplatzVerlassen() {
        initComponents();
        btnVerlassen.setEnabled(false);
        setDefaultCloseOperation(ParkplatzVerlassen.DISPOSE_ON_CLOSE);

    }
    // Datum und Uhrzeit Spinners werden hier konfiguriert.

    // Überprüft die Textfelder und aktiviert/deaktiviert den "Verlassen"-Button.
    public void validateFields() {
        String vorname = txtVorname.getText();
        String nachname = txtNachname.getText();
        String nummerschild = txtSchildsnummer.getText();

        if (!vorname.equals("") && (!nachname.equals("")) && !nummerschild.equals("")) {
            btnVerlassen.setEnabled(true);
        } else {
            btnVerlassen.setEnabled(false);

        }
    }

    private void resetFormular() {
        txtVorname.setText("");
        txtNachname.setText("");
        txtSchildsnummer.setText("");

    }
    // Löscht den Inhalt der Textfelder und deaktiviert den Button.

    public void clear() {
        txtVorname.setText("");
        txtNachname.setText("");
        txtSchildsnummer.setText("");

        btnVerlassen.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVerlassen = new javax.swing.JButton();
        txtVorname = new javax.swing.JTextField();
        txtSchildsnummer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNachname = new javax.swing.JTextField();
        btnAbbrechen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Vorname der Besitzer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 190, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Schildsnummer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, 20, 20));

        btnVerlassen.setBackground(new java.awt.Color(58, 101, 143));
        btnVerlassen.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnVerlassen.setForeground(new java.awt.Color(255, 255, 255));
        btnVerlassen.setText("Parkplatz Verlassen");
        btnVerlassen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerlassenActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerlassen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, 30));

        txtVorname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVornameKeyReleased(evt);
            }
        });
        getContentPane().add(txtVorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 390, -1));

        txtSchildsnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSchildsnummerKeyReleased(evt);
            }
        });
        getContentPane().add(txtSchildsnummer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 390, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nachname");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 140, 30));

        txtNachname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNachnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtNachname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 390, -1));

        btnAbbrechen.setBackground(new java.awt.Color(58, 101, 143));
        btnAbbrechen.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnAbbrechen.setForeground(new java.awt.Color(255, 255, 255));
        btnAbbrechen.setText("Abbrechen");
        btnAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbbrechenActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbbrechen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 110, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("_");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, -10, 30, 30));

        jButton1.setBackground(new java.awt.Color(135, 135, 79));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Zurück zu Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 523, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/Background_Big.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerlassenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerlassenActionPerformed
        // TODO add your handling code here:
        String nummernschild = txtSchildsnummer.getText();

        if (nummernschild.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bitte geben Sie die Schildnummer ein.", "Fehler", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String ausfahrZeitpunkt = dateFormat.format(new Date());

        boolean erfolgreich = DBOperations.verlassenParkplatz(nummernschild, ausfahrZeitpunkt);

        if (erfolgreich) {
            JOptionPane.showMessageDialog(this, "Der Parkplatz wurde erfolgreich verlassen.", "Erfolg", JOptionPane.INFORMATION_MESSAGE);
            resetFormular();
        } else {
            JOptionPane.showMessageDialog(this, "Fehler beim Verlassen des Parkplatzes oder das Fahrzeug wurde nicht gefunden.", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerlassenActionPerformed

    private void btnAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbbrechenActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_btnAbbrechenActionPerformed

    private void txtVornameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVornameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtVornameKeyReleased

    private void txtNachnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNachnameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtNachnameKeyReleased

    private void txtSchildsnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSchildsnummerKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtSchildsnummerKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        setExtendedState(ParkplatzVerlassen.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkplatzVerlassen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkplatzVerlassen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkplatzVerlassen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkplatzVerlassen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkplatzVerlassen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbbrechen;
    private javax.swing.JButton btnVerlassen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtNachname;
    private javax.swing.JTextField txtSchildsnummer;
    private javax.swing.JTextField txtVorname;
    // End of variables declaration//GEN-END:variables
}
